### ISSUE TITLE
Ill-formed PyPI source tarballs for pyproject.toml (v0.1.23)

### ISSUE THREAD

**Issue by wdconinc** [eic/firebird#27]
### Environment: (where does this bug occur, have you tried other environments)
- Which branch (often `main` for latest released): main
- Which version (or `HEAD` for the most recent on git): 0.1.23
- Any specific OS or system where the issue occurs?
- Any special versions of ROOT or Geant4?

### Steps to reproduce: (give a step by step account of how to trigger the bug)
1. `wget https://files.pythonhosted.org/packages/52/36/5eabc1e04e80cb659e0d45674e4b55c114217c7704848f26f08dfcd814d3/pyrobird-0.1.23.tar.gz`
2. `tar -zxvf pyrobird-0.1.23.tar.gz`
3. `cd pyrobird-0.1.23`
4. `hatchling build`

### Expected Result: (what do you expect when you execute the steps above)
Should generate a full dist tarball with useful content

### Actual Result: (what do you get when you execute the steps above)
Misses everything in the `pyrobird/` directory since the `pyproject.toml` refers to `src/pyrobird`.

**Comment by veprbl** [comment]
I get:
```
# tar tzf dist/pyrobird-0.1.23.tar.gz
pyrobird-0.1.23/pyrobird/__about__.py
pyrobird-0.1.23/pyrobird/__init__.py
pyrobird-0.1.23/pyrobird/cern_root.py
pyrobird-0.1.23/pyrobird/edm4eic.py
pyrobird-0.1.23/pyrobird/cli/__init__.py
pyrobird-0.1.23/pyrobird/cli/__main__.py
pyrobird-0.1.23/pyrobird/cli/convert.py
pyrobird-0.1.23/pyrobird/cli/geo.py
pyrobird-0.1.23/pyrobird/cli/screenshot.py
pyrobird-0.1.23/pyrobird/cli/serve.py
pyrobird-0.1.23/pyrobird/data/eic_geo_process_rules.yaml
pyrobird-0.1.23/pyrobird/server/__init__.py
pyrobird-0.1.23/.gitignore
pyrobird-0.1.23/LICENSE.txt
pyrobird-0.1.23/README.md
pyrobird-0.1.23/pyproject.toml
pyrobird-0.1.23/PKG-INFO
```
what is missing?

**Comment by wdconinc** [comment]
```
$ tar tzf dist/pyrobird-0.1.23.tar.gz
pyrobird-0.1.23/.gitignore
pyrobird-0.1.23/LICENSE.txt
pyrobird-0.1.23/README.md
pyrobird-0.1.23/pyproject.toml
pyrobird-0.1.23/PKG-INFO
```

**Comment by wdconinc** [comment]
hatchling-1.25.0

**Comment by wdconinc** [comment]
Note that this applies to the source tarball from pypi.org, not the git repository. The git repo works:
```
13:39:41 wdconinc@menelaos ~/git/firebird/pyrobird $ tar tzf dist/pyrobird-0.1.23.tar.gz
pyrobird-0.1.23/pyrobird/__about__.py
pyrobird-0.1.23/pyrobird/__init__.py
pyrobird-0.1.23/pyrobird/cern_root.py
pyrobird-0.1.23/pyrobird/edm4eic.py
pyrobird-0.1.23/pyrobird/cli/__init__.py
pyrobird-0.1.23/pyrobird/cli/__main__.py
pyrobird-0.1.23/pyrobird/cli/convert.py
pyrobird-0.1.23/pyrobird/cli/geo.py
pyrobird-0.1.23/pyrobird/cli/screenshot.py
pyrobird-0.1.23/pyrobird/cli/serve.py
pyrobird-0.1.23/pyrobird/data/eic_geo_process_rules.yaml
pyrobird-0.1.23/pyrobird/server/__init__.py
pyrobird-0.1.23/.gitignore
pyrobird-0.1.23/LICENSE.txt
pyrobird-0.1.23/README.md
pyrobird-0.1.23/pyproject.toml
pyrobird-0.1.23/PKG-INFO
```

**Comment by veprbl** [comment]
Oh, okay, so in git it's ./src/pyrobird, but in sdist it's ./pyrobird.

**Comment by wdconinc** [comment]
Yes, and I don't have experience with how pypi creates an sdist from what it gets.

**Comment by wdconinc** [comment]
(temporarily I'm just creating a symlink src -> . )
